# Generated by Django 5.1.4 on 2025-10-18 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('bronze', 'Bronce'), ('silver', 'Plata'), ('gold', 'Oro'), ('platinum', 'Platino'), ('vip', 'VIP')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('benefits', models.JSONField(default=dict, help_text='Beneficios en formato JSON')),
                ('min_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_monthly_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-min_balance'],
            },
        ),
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to='players.player')),
                ('from_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='memberships.membershipplan')),
                ('to_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='memberships.membershipplan')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('total_wagered', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_won', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_membership', to='players.player')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.membershipplan')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
    ]
